function fence(value) {
  const text = String(value ?? '');
  return text.includes('```') ? '````' : '```';
}

function block(label, value, language = 'text') {
  const text = String(value ?? '').trim();
  if (!text) return `> ${label}: _none_`;
  const marker = fence(text);
  return `### ${label}\n\n${marker}${language}\n${text}\n${marker}`;
}

export function renderMarkdown(brief, { title = 'Agent handoff brief' } = {}) {
  const files = brief.files.length ? brief.files.map((file) => '- `' + file.status + '` `' + file.path + '`').join('\n') : '- _No changed files detected_';
  const warning = brief.redactions ? `> 🔒 ${brief.redactions} secret-shaped value(s) redacted locally before writing this brief.\n` : '';
  return `# ${title}\n\n> Generated by [agentbrief](https://github.com/jovial-liu/agentbrief). This file is designed to be pasted into a coding-agent task.\n\n${warning}## Goal\n\n${brief.goal || '_No goal provided_'}\n\n## Repository snapshot\n\n- Branch: \`${brief.repository.branch || 'detached/unknown'}\`\n- Diff stat: ${brief.repository.stat || '_clean or unavailable_'}\n- Truncated: ${brief.truncated ? 'yes' : 'no'}\n\n## Changed files\n\n${files}\n\n${block('Command / reproduction', brief.evidence.command)}\n\n${block('Observed log or evidence', brief.evidence.log)}\n\n${block('Patch context', brief.diff, 'diff')}\n\n## Handoff checklist\n\n- Confirm the goal and constraints before editing.\n- Reproduce the reported behavior when a command is listed.\n- Inspect the changed files above before making a new patch.\n- Update this brief after the next meaningful checkpoint.\n`;
}

export function renderJson(brief) { return JSON.stringify(brief, null, 2); }
